### ISSUE TITLE
Fetch API cannot load webpack-internal:///./node_modules/react/cjs/react.development.js. URL scheme must be "http" or "https" for CORS request

### ISSUE THREAD

**Issue by mattd429** [mattd429/flask-apollo-react-hooks-docker-graphql#20]
```log
Fetch API cannot load webpack-internal:///./node_modules/react/cjs/react.development.js. URL scheme must be "http" or "https" for CORS request
```
only happens when bundle.js is present in dev mode.

**Comment by GerardSuch** [comment]
I'm also having the same/similar message.

After a few hours trying to see what was failing in my code I haven't been able to find anything. In my case this is triggered when I run setState, while in the render I am deciding what to return based on the updated State value.

`Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/react-dom/cjs/react-dom.development.js?. URL scheme must be "http" or "https" for CORS request.`

**Comment by GerardSuch** [comment]
Sorry, forget about this, I see now that any error of my code gets this message. At first it was forgetting about writting `this.props` instead of `props`, and now it's another thing. The message however is the same.

**Comment by mattd429** [comment]
if anything changes ill post results here.  thanks

**Comment by wallawe** [comment]
Running into this same issue, were either of you able to figure it out?

**Comment by mattd429** [comment]
@wallawe sorry i have not been able to resolve this, please let me or @GerardSuch  know if you fix this issue, maybe even submit a legit issue since i did not attend for this issue to go anywhere.

thanks,

**Comment by yjaquinas** [comment]
Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/react-dom/cjs/react-dom.development.js?. URL scheme must be "http" or "https" for CORS request.

**Comment by coolliyong** [comment]
Can you solve this problem?

How did this problem arise? Is it generated by dynamically loading Javascript?

**Comment by MrMoehner** [comment]
Having the same problem. I tried updating everything to the latest version, nothing works yet:-(
I am trying to install the following DataGrid into a NextJS App when i run into this problem.
https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/tree-data/

Help is highly recommended!

**Comment by mattd429** [comment]
@MrMoehner are you by chance running a docker build? that is when the error occurs for me.

**Comment by MrMoehner** [comment]
> 
> 
> @MrMoehner are you by chance running a docker build? that is when the error occurs for me.

@mattd429 : No, its locally installed, no docker involved. But i figured out, that i get the same message with all kinds of uncaught errors. For example when i mess up JSON.parse with the wrong object. I will keep you informed as soon as i find a way around.

**Comment by lizandroconde** [comment]
add 
`headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
  }`

**Comment by valdeniomarinho** [comment]
> add
> `headers: { 'Accept': 'application/json', 'Content-Type': 'application/json', }`

I also tried this, but it not worked. Anyone with a solution for this?

**Comment by Gosttlt** [comment]
https://github.com/vercel/next.js/issues/6374
